import type { GameHeader } from "@yogan-hockey/schemas";

/**
 * The slot for the pick on a game page (#53 fills it). The page's server component renders it
 * once and hands it to `GamePage`, which shows it as a section of the scheduled page and as "the
 * pick" tab of the Game Stream and the finished game.
 *
 * #53 reads the game's Prediction from D1 by `gameId` here: the team, probability, reasoning and
 * key factors with the line "generated by AI, for fun", "pick pending" until it arrives, nothing
 * when it failed, and right or wrong from `header` once the game is final.
 */
export function GamePick({ header }: { gameId: string; header: GameHeader }) {
  return (
    <p data-slot="game-pick-pending" className="max-w-prose text-foreground/70">
      {header.status === "scheduled" ? "pick pending" : "No pick was made for this game."}
    </p>
  );
}
