import type { FinalGame, GameHeader, MadePrediction } from "@yogan-hockey/schemas";
import { pickOutcome } from "@yogan-hockey/schemas";
import { Badge } from "@yogan-hockey/ui/components/badge";
import { finalResult, pickedSide } from "../../lib/picks";
import { LocalTime } from "../local-time";

/**
 * The whole pick on a game page, the Reference UI's third tab: the picked team and its win
 * probability in bold, running into the reasoning; then the key factors, and when it was made
 * with the line "generated by AI, for fun". The page's server component renders it once and
 * `GamePage` shows it as "The pick" section of a game still to come and as "the pick" tab after.
 *
 * `final` is the game's row in D1, there once the game is over and written: with it the pick is
 * marked right or wrong, above the rest. Until then, a live game included, it is unmarked.
 *
 * Draws nothing for a pick whose team is not in the game.
 */
export function GamePick({
  prediction,
  header,
  final,
}: {
  prediction: MadePrediction;
  header: GameHeader;
  final: FinalGame | null;
}) {
  const side = pickedSide(prediction, header);
  if (side == null) return null;
  const outcome = pickOutcome(prediction, final);
  return (
    <div data-slot="game-pick-full" className="max-w-prose space-y-3">
      {outcome != null && final != null && (
        <p data-slot="pick-outcome" data-outcome={outcome} className="flex items-center gap-2">
          <Badge variant={outcome === "right" ? "default" : "outline"}>{outcome}</Badge>
          <span className="text-foreground/70">{finalResult(final)}</span>
        </p>
      )}
      <p>
        <b data-slot="pick-lead">
          {side.name} {Math.round(prediction.winProbability)}%.
        </b>{" "}
        {prediction.reasoning}
      </p>
      {prediction.keyFactors.length > 0 && (
        <ul data-slot="pick-factors" className="text-foreground/70">
          {prediction.keyFactors.map((factor) => (
            <li key={factor} className="flex gap-2">
              <span aria-hidden="true">-</span>
              {factor}
            </li>
          ))}
        </ul>
      )}
      <p data-slot="pick-made" className="text-foreground/50">
        made <LocalTime at={prediction.madeAt} show="day" />,{" "}
        <LocalTime at={prediction.madeAt} show="time" /> · generated by AI, for fun
      </p>
    </div>
  );
}
