packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  workerd: true
  core-js-pure: false
  sharp: false

minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20261006.1'
  - '@shadcn/registry@0.1.2'
  - shadcn@4.21.3
