import { expect, test } from "@playwright/test";

// The rows are the sample picks `picks.setup.ts` seeded (`apps/web/lib/sample-picks.ts`):
// Toronto at 58% over Nashville, a failed Prediction for 401892450, Dallas over Buffalo in the
// recorded final (which Dallas won in a shootout), and a season record of 3 right, 2 wrong.
const SCHEDULED_GAME = "401892449";
const FAILED_GAME = "401892450";
const FINAL_GAME = "401803652";

test.use({ timezoneId: "America/Toronto" });

test("the pick is on the game rows, the scheduled game page and the Replay, and a failed one shows nothing", async ({
  page,
}) => {
  // The dashboard: the one-line pick in the note, and the season record in Tonight's header.
  await page.goto("/");
  const tonight = page.getByRole("region", { name: "Tonight" });
  const row = (id: string) =>
    tonight.getByRole("row").filter({ has: page.locator(`a[href="/nhl/games/${id}"]`) });
  await expect(row(SCHEDULED_GAME).locator('[data-slot="game-pick"]')).toHaveText("TOR 58%");
  await expect(tonight.locator('[data-slot="picks-record"]')).toHaveText("picks: 3 right, 2 wrong");
  // A failed Prediction: the row is there and says nothing of a pick.
  await expect(row(FAILED_GAME)).toHaveCount(1);
  await expect(row(FAILED_GAME).locator('[data-slot="game-pick"]')).toHaveCount(0);
  await expect(tonight).not.toContainText("pick pending");

  // Every other list of games says the same.
  await page.goto("/nhl/live");
  const upcoming = page.getByRole("region", { name: "Upcoming" });
  await expect(
    upcoming
      .getByRole("row")
      .filter({ has: page.locator(`a[href="/nhl/games/${SCHEDULED_GAME}"]`) })
      .locator('[data-slot="game-pick"]'),
  ).toHaveText("TOR 58%");

  // The scheduled game page: all of it.
  await page.goto(`/nhl/games/${SCHEDULED_GAME}`);
  const pick = page.locator('[data-slot="game-pick"]');
  await expect(pick.getByRole("heading")).toHaveText("The pick");
  await expect(pick.locator('[data-slot="pick-lead"]')).toHaveText("Toronto Maple Leafs 58%.");
  await expect(pick).toContainText("They have the better record");
  await expect(pick.locator('[data-slot="pick-factors"] li')).toHaveCount(3);
  await expect(pick.locator('[data-slot="pick-made"]')).toHaveText(
    "made Tue Oct 6, 12:02 PM · generated by AI, for fun",
  );
  await expect(pick.locator('[data-slot="pick-outcome"]')).toHaveCount(0);

  // (A failed Prediction's game page has no recording to open: `lib/game-pick.test.ts` has it.)

  // The Replay: the pick tab, marked right from the final score in D1.
  await page.goto(`/nhl/games/${FINAL_GAME}?tab=pick`);
  const tab = page.locator('[data-slot="game-tab"]');
  await expect(tab.locator('[data-slot="pick-lead"]')).toHaveText("Dallas Stars 55%.");
  await expect(tab.locator('[data-slot="pick-outcome"]')).toHaveText("rightDallas Stars won 4-3");
  await expect(tab).toContainText("generated by AI, for fun");
});
