#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Issue #32, "Cloudflare account setup". Run from anywhere inside the repo:
#
#   ./scripts/account-setup.sh
#
# Safe to rerun: every stage looks for what already exists before it creates
# anything, and asks before each change. Names and ids are remembered in
# .env.local (gitignored). No secret is ever printed: the API token is typed
# hidden, and the ntfy topic is read from .env.local when the phone needs it.

TOTAL_STAGES=11

ISSUE=32
ZONE_NAME="yogan.dev"
SITE_HOST="hockey.yogan.dev"
KV_TITLE="yogan-hockey-cache"
KV_PREVIEW_TITLE="yogan-hockey-cache-preview"
D1_NAME="yogan-hockey"
D1_PREVIEW_NAME="yogan-hockey-preview"
AI_GATEWAY_NAME="yogan-hockey"
ACCESS_APP_NAME="Yogan Hockey"
ACCESS_POLICY_NAME="Owner only"
API_TOKEN_NAME="yogan-hockey-2026 GitHub Actions"
COMMENT_MARKER="<!-- account-setup-wizard -->"

# Everything the last stage records. Empty means "not done".
REPO=""; CLOUDFLARE_ACCOUNT_ID=""; CI_TOKEN=""; WORKERS_PAID=""
KV_ID=""; KV_PREVIEW_ID=""; D1_ID=""; D1_PREVIEW_ID=""; AI_GATEWAY_ID=""
ZONE_ID=""; ZONE_STATUS=""; DNS_RECORDS=""
ACCESS_EMAIL=""; ACCESS_APP_ID=""; ACCESS_AUD=""; ACCESS_TEAM_DOMAIN=""; ACCESS_POLICY=""
NTFY_TOPIC=""; NTFY_PHONE=""; WORKER_NAME=""; WORKER_SECRET=""
TOKEN_SECRET=""; ACCOUNT_SECRET=""; NTFY_SECRET=""; BRANCH_PROTECTION=""

cd "$(git rev-parse --show-toplevel)"
ENV_FILE=".env.local"

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
CF_ERR="$TMP/cf.err"

# ── Helpers for these stages ──────────────────────────────────────────────

ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# todo "what is left": warn now and list it in the closing summary.
todo() { SKIPPED+=("$1"); warn "not done: $1"; }

# cfq ARGS...: run cf without a terminal on stdin. JSON goes to stdout, cf's
# error text to $CF_ERR.
cfq() { cf "$@" </dev/null 2>"$CF_ERR"; }

# cf_error: show why the last cfq failed. Never call it after a command that
# was given a secret.
cf_error() { sed -e '/^[[:space:]]*$/d' -e 's/^/      /' "$CF_ERR" | head -n 8; }

# ask_default KEY "Prompt" DEFAULT: like ask, with a fallback default.
ask_default() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  current="${current:-$3}"
  printf '  %s%s%s %s[%s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "${input:-$current}"
}

# The find_* functions print the id of the named resource, or nothing if it
# does not exist. They fail only if the listing itself failed.
find_kv() {
  cfq kv namespaces list --per-page 1000 |
    jq -r --arg n "$1" 'first(.[] | select(.title == $n) | .id) // empty'
}
find_d1() {
  cfq d1 list --name "$1" |
    jq -r --arg n "$1" 'first(.[] | select(.name == $n) | .uuid) // empty'
}
find_gateway() {
  cfq ai-gateway gateways list --search "$1" |
    jq -r --arg n "$1" 'first(.[] | select(.id == $n) | .id) // empty'
}
create_kv()      { cfq kv namespaces create --title "$1" >/dev/null; }
create_d1()      { cfq d1 create --name "$1" >/dev/null; }
# Logging on; no caching (a Prediction is made once) and no rate limit (the
# daily cap is enforced in our own code). The API requires all four fields.
create_gateway() {
  cfq ai-gateway gateways create --id "$1" --collect-logs \
    --cache-ttl 0 --cache-invalidate-on-update=false \
    --rate-limiting-interval 0 --rate-limiting-limit 0 >/dev/null
}

# ensure KEY "label" find_fn create_fn NAME: find the resource or offer to
# create it, then remember its id in $KEY and in ENV_FILE.
ensure() {
  local key="$1" label="$2" find="$3" create="$4" name="$5" id
  if ! id=$("$find" "$name"); then
    cf_error; todo "$label \"$name\" (could not list; rerun)"; return 0
  fi
  if [[ -n "$id" ]]; then
    ok "$label \"$name\" already exists"
  elif ! confirm "Create $label \"$name\"?"; then
    todo "$label \"$name\""; return 0
  elif "$create" "$name" && id=$("$find" "$name") && [[ -n "$id" ]]; then
    ok "created $label \"$name\""
  else
    cf_error; todo "$label \"$name\" (create failed; make it in the dashboard with this exact name and rerun)"
    return 0
  fi
  printf -v "$key" '%s' "$id"
  write_env "$key" "$id"
}

# has_gh_secret NAME: is a repository Actions secret of that name set?
has_gh_secret() {
  gh secret list --repo "$REPO" --json name -q '.[].name' 2>/dev/null | grep -qx "$1"
}

# verify_token TOKEN: ask Cloudflare whether the token is active. The token
# reaches curl on stdin, so it never appears in a process list.
verify_token() {
  local token="$1" url
  [[ "$token" =~ ^[A-Za-z0-9_-]{30,}$ ]] || return 1
  for url in \
    "https://api.cloudflare.com/client/v4/user/tokens/verify" \
    "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/tokens/verify"; do
    if printf 'header = "Authorization: Bearer %s"\n' "$token" |
      curl -sS -K - "$url" 2>/dev/null |
      jq -e '.success and .result.status == "active"' >/dev/null 2>&1; then
      return 0
    fi
  done
  return 1
}

# ntfy_push TOPIC MESSAGE: send a push. The topic reaches curl on stdin.
ntfy_push() {
  printf 'url = "https://ntfy.sh/%s"\n' "$1" |
    curl -fsS -K - -H "Title: Yogan Hockey" -d "$2" >/dev/null 2>&1
}

# ──────────────────────────────────────────────────────────────────────────

banner "Yogan Hockey 2026: Cloudflare account setup (issue #$ISSUE)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools and logins this wizard drives."
for tool in cf gh jq openssl curl; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is not installed."
done
git check-ignore -q "$ENV_FILE" || die "$ENV_FILE is not gitignored; refusing to write ids and the ntfy topic to it."
ok "$ENV_FILE is gitignored"

cfq auth whoami >"$TMP/whoami.json" || die "cf is not logged in. Run: cf auth login"
jq -e '.authenticated and .tokenValid' "$TMP/whoami.json" >/dev/null ||
  die "cf's login has expired. Run: cf auth login"
ok "cf is logged in"

gh auth status >/dev/null 2>&1 || die "gh is not logged in. Run: gh auth login"
REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner)
gh secret list --repo "$REPO" --json name >/dev/null 2>&1 ||
  die "gh cannot list the Actions secrets of $REPO. Check: gh auth status"
ok "gh is logged in; repository $REPO"

mapfile -t account_ids < <(jq -r '.accounts[].id' "$TMP/whoami.json")
case "${#account_ids[@]}" in
  0) die "cf sees no Cloudflare account." ;;
  1) CLOUDFLARE_ACCOUNT_ID="${account_ids[0]}" ;;
  *)
    say "cf can see more than one account:"
    jq -r '.accounts | to_entries[] | "    \(.key + 1)) \(.value.name)  \(.value.id)"' "$TMP/whoami.json"
    pick=""
    until [[ "$pick" =~ ^[1-9][0-9]*$ ]] && (( pick <= ${#account_ids[@]} )); do
      printf '  %sWhich account holds %s? Number:%s ' "$BOLD" "$ZONE_NAME" "$RESET"
      read -r pick || die "No account chosen."
    done
    CLOUDFLARE_ACCOUNT_ID="${account_ids[pick - 1]}"
    ;;
esac
export CLOUDFLARE_ACCOUNT_ID
ok "Cloudflare account $CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Workers Paid"
say "The site needs the Workers Paid plan (about \$5 a month)."
is_paid() {
  cfq accounts subscriptions get |
    jq -e 'any(.[]; .rate_plan.id == "workers_paid")' >/dev/null 2>&1
}
if is_paid; then
  ok "the account is already on Workers Paid"
  WORKERS_PAID="yes"
else
  warn "cf does not list a Workers Paid subscription on this account."
  open_url "https://dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/workers/plans"
  step "If that link misses, go to Workers & Pages, then Plans, in the dashboard."
  step "Choose the Workers Paid plan and complete the purchase."
  while true; do
    if ! confirm "Purchased? Check again (n skips this stage)"; then
      todo "Workers Paid plan"; break
    fi
    if is_paid; then ok "Workers Paid is active"; WORKERS_PAID="yes"; break; fi
    warn "still not listed; it can take a minute."
  done
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "KV and D1: production and preview"
say "One KV namespace and one D1 database for production, and one pair that"
say "previews share. Per-pull-request stores, if they work, are made by the"
say "deploy pipeline (#33), not here."
ensure KV_ID         "KV namespace" find_kv create_kv "$KV_TITLE"
ensure KV_PREVIEW_ID "KV namespace" find_kv create_kv "$KV_PREVIEW_TITLE"
ensure D1_ID         "D1 database"  find_d1 create_d1 "$D1_NAME"
ensure D1_PREVIEW_ID "D1 database"  find_d1 create_d1 "$D1_PREVIEW_NAME"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "$SITE_HOST on the $ZONE_NAME zone"
say "The Worker does not exist yet, so nothing can be attached today. The"
say "hostname becomes a Worker custom domain on the first deploy (#33). This"
say "stage checks the zone is ready for that."
if zone=$(cfq zones list --name "$ZONE_NAME" | jq -c --arg n "$ZONE_NAME" 'first(.[] | select(.name == $n)) // empty') && [[ -n "$zone" ]]; then
  ZONE_ID=$(jq -r '.id' <<<"$zone")
  ZONE_STATUS=$(jq -r '.status' <<<"$zone")
  write_env CLOUDFLARE_ZONE_ID "$ZONE_ID"
  if [[ "$ZONE_STATUS" == "active" ]]; then ok "zone $ZONE_NAME is active"
  else todo "zone $ZONE_NAME has status \"$ZONE_STATUS\"; it must be active"; fi
  if [[ "$(jq -r '.account.id' <<<"$zone")" != "$CLOUDFLARE_ACCOUNT_ID" ]]; then
    todo "zone $ZONE_NAME belongs to a different account than the one chosen in stage 1"
  fi
  if records=$(cfq dns records list --zone "$ZONE_NAME" --name "$SITE_HOST" | jq -r '[.[] | .type] | join(", ")'); then
    if [[ -z "$records" ]]; then
      ok "no DNS record holds $SITE_HOST yet, so the custom domain can take it"
      DNS_RECORDS="none"
    else
      DNS_RECORDS="$records"
      warn "$SITE_HOST already has DNS record(s): $records"
      note "Fine if the Worker's custom domain made them (after #33). Otherwise"
      note "delete them before the first deploy, or the custom domain will not attach."
    fi
  else
    cf_error; todo "could not list DNS records for $SITE_HOST"
  fi
else
  cf_error; todo "zone $ZONE_NAME was not found on this account"
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare Access in front of $SITE_HOST"
say "One Access application on $SITE_HOST with one policy: allow your email,"
say "nobody else. The address is kept in $ENV_FILE and is not recorded on the issue."
ask ACCESS_EMAIL "Your email, the only one allowed in:"
while [[ ! "$ACCESS_EMAIL" =~ ^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$ ]]; do
  [[ -n "$ACCESS_EMAIL" ]] || die "No email given. Rerun when ready; nothing done so far is lost."
  warn "that does not look like an email address."
  ask ACCESS_EMAIL "Your email, the only one allowed in:"
done
write_env ACCESS_EMAIL "$ACCESS_EMAIL"

find_access_app() {
  cfq zero-trust access applications list --domain "$SITE_HOST" |
    jq -c --arg d "$SITE_HOST" 'first(.[] | select(
        .domain == $d or ((.domain // "") | startswith($d + "/"))
        or ((.self_hosted_domains // []) | any(. == $d or startswith($d + "/")))
      )) // empty'
}
access_dashboard="https://one.dash.cloudflare.com/$CLOUDFLARE_ACCOUNT_ID/access/apps"
app=""
if ! app=$(find_access_app); then
  cf_error; todo "Access application (could not list; rerun)"
elif [[ -n "$app" ]]; then
  ok "an Access application for $SITE_HOST already exists"
elif confirm "Create the Access application \"$ACCESS_APP_NAME\" on $SITE_HOST?"; then
  jq -n --arg n "$ACCESS_APP_NAME" --arg d "$SITE_HOST" \
    '{name: $n, domain: $d, type: "self_hosted", session_duration: "730h"}' >"$TMP/app.json"
  if cfq zero-trust access applications create --body "@$TMP/app.json" >/dev/null &&
    app=$(find_access_app) && [[ -n "$app" ]]; then
    ok "created the Access application"
  else
    cf_error; app=""
    todo "Access application (create failed; make a self-hosted application for $SITE_HOST at $access_dashboard and rerun)"
  fi
else
  todo "Access application for $SITE_HOST"
fi

if [[ -n "$app" ]]; then
  ACCESS_APP_ID=$(jq -r '.id' <<<"$app")
  ACCESS_AUD=$(jq -r '.aud' <<<"$app")
  if [[ "$(jq '.policies // [] | length' <<<"$app")" == "0" ]]; then
    say "The application has no policy yet, so nobody can get in."
    if confirm "Add the policy \"$ACCESS_POLICY_NAME\": allow only $ACCESS_EMAIL?"; then
      jq -n --arg n "$ACCESS_POLICY_NAME" --arg e "$ACCESS_EMAIL" \
        '{name: $n, decision: "allow", include: [{email: {email: $e}}]}' >"$TMP/policy.json"
      if cfq zero-trust access applications policies create "$ACCESS_APP_ID" --body "@$TMP/policy.json" >/dev/null; then
        ok "added the policy"
        refreshed=$(find_access_app || true)
        [[ -n "$refreshed" ]] && app="$refreshed"
      else
        cf_error
      fi
    fi
  fi
  # Exactly one policy, an allow, whose only rule is that one email.
  if jq -e --arg e "$ACCESS_EMAIL" '
      (.policies // []) as $p
      | ($p | length) == 1
      and $p[0].decision == "allow"
      and ($p[0].include | length) == 1
      and (($p[0].include[0].email.email // "") | ascii_downcase) == ($e | ascii_downcase)
      and (($p[0].exclude // []) | length) == 0
      and (($p[0].require // []) | length) == 0' <<<"$app" >/dev/null 2>&1; then
    ok "the only policy allows that one email and nothing else"
    ACCESS_POLICY="one allow policy, one email"
  else
    warn "the policies on this application are not \"allow that one email only\":"
    jq -r '(.policies // [])[] | "      \(.name): \(.decision), \(.include | length) include rule(s)"' <<<"$app" || true
    open_url "$access_dashboard"
    step "Open the $SITE_HOST application, then its Policies tab."
    step "Leave exactly one policy: action Allow, one Include rule, Emails, your address."
    todo "Access policy needs fixing by hand, then rerun to confirm"
  fi
  if org=$(cfq zero-trust organizations list); then
    ACCESS_TEAM_DOMAIN=$(jq -r '(if type == "array" then .[0] else . end) | .auth_domain // empty' <<<"$org")
  fi
  note "Login is by one-time PIN to your email unless you have set up another"
  note "identity provider. It gets its real test in #33, once the site answers."
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "AI Gateway for the Predictions"
say "A gateway with logging on, so every prompt and response is kept. The"
say "Worker's AI binding is pointed at it by name in #52."
ensure AI_GATEWAY_ID "AI Gateway" find_gateway create_gateway "$AI_GATEWAY_NAME"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "GitHub Actions: Cloudflare API token and account id"
say "CI deploys with a scoped token. cf's own login is not allowed to mint"
say "tokens, so this one is made in the dashboard."
set_secret CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
has_gh_secret CLOUDFLARE_ACCOUNT_ID && ACCOUNT_SECRET="set"

if has_gh_secret CLOUDFLARE_API_TOKEN && ! confirm "CLOUDFLARE_API_TOKEN is already a GitHub secret. Replace it with a new token?"; then
  ok "keeping the existing CLOUDFLARE_API_TOKEN"
  TOKEN_SECRET="set"
else
  open_url "https://dash.cloudflare.com/profile/api-tokens"
  step "If a token named \"$API_TOKEN_NAME\" is already listed, delete it first."
  step "Create Token, then use the \"Edit Cloudflare Workers\" template."
  step "Rename it to: $API_TOKEN_NAME"
  step "Add two Account permissions: D1 = Edit, and Workers AI = Read."
  step "Account Resources: Include, only this account."
  step "Zone Resources: Include, Specific zone, $ZONE_NAME."
  step "Continue to summary, Create Token. The value is shown once: copy it."
  note "If #33's first deploy reports a missing permission, edit this token in"
  note "the dashboard; its value does not change."
  ask_secret CI_TOKEN "Paste the token (input is hidden):"
  if [[ -z "$CI_TOKEN" ]]; then
    todo "GitHub secret CLOUDFLARE_API_TOKEN"
  elif verify_token "$CI_TOKEN" || confirm "Cloudflare did not confirm that token as active. Store it anyway?"; then
    set_secret CLOUDFLARE_API_TOKEN "$CI_TOKEN"
    has_gh_secret CLOUDFLARE_API_TOKEN && TOKEN_SECRET="set"
  else
    todo "GitHub secret CLOUDFLARE_API_TOKEN"
  fi
  CI_TOKEN=""
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "ntfy topic"
say "Alerts go to a topic on ntfy.sh. Anyone who knows the topic can read and"
say "send to it, so it is long, random and treated as a secret."
NTFY_TOPIC=$(_existing NTFY_TOPIC || true)
if [[ -n "$NTFY_TOPIC" ]]; then
  ok "reusing the topic already in $ENV_FILE"
elif has_gh_secret NTFY_TOPIC && ! confirm "GitHub already has NTFY_TOPIC but $ENV_FILE does not. Make a new topic, replacing it everywhere?"; then
  note "Leaving the existing topic alone. This machine does not know its value,"
  note "so the phone test and the Worker secret are skipped."
  NTFY_SECRET="set"
else
  NTFY_TOPIC="yogan-hockey-$(openssl rand -hex 24)"
  write_env NTFY_TOPIC "$NTFY_TOPIC"
  ok "generated a new topic (not shown)"
fi

if [[ -n "$NTFY_TOPIC" ]]; then
  set_secret NTFY_TOPIC "$NTFY_TOPIC"
  has_gh_secret NTFY_TOPIC && NTFY_SECRET="set"
  # A fingerprint of the topic, so a rerun knows the phone was checked against
  # this topic without keeping a second copy of it.
  topic_hash=$(printf '%s' "$NTFY_TOPIC" | openssl dgst -sha256 -r | cut -d' ' -f1)
  if [[ "$(_existing NTFY_PHONE_CONFIRMED || true)" == "$topic_hash" ]]; then
    ok "your phone was already confirmed on this topic"
    NTFY_PHONE="subscribed, test push received"
  else
    say "Now your phone. The topic is not printed here: open $ENV_FILE in your"
    say "editor and copy the value of NTFY_TOPIC."
    step "Install the ntfy app (Android or iOS) and tap +."
    step "Subscribe to that topic on the default server, ntfy.sh."
    if ! confirm "Subscribed? Send a test push to the topic now"; then
      todo "ntfy: phone subscription not confirmed (rerun to test it)"
    elif ! ntfy_push "$NTFY_TOPIC" "Account setup wizard: test push"; then
      todo "ntfy: could not send the test push (is ntfy.sh reachable?)"
    elif confirm "Did it arrive on your phone?"; then
      ok "phone is subscribed"
      NTFY_PHONE="subscribed, test push received"
      write_env NTFY_PHONE_CONFIRMED "$topic_hash"
    else
      todo "ntfy: the test push did not reach the phone (rerun to try again)"
    fi
  fi
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "ntfy topic as a Worker secret"
say "The Worker reads the topic from a secret named NTFY_TOPIC. A secret can"
say "only be put on a Worker that has been deployed once."
ask_default WORKER_NAME "Worker name (the name in apps/web/cloudflare.config.ts):" "yogan-hockey"
write_env WORKER_NAME "$WORKER_NAME"
if [[ -z "$NTFY_TOPIC" ]]; then
  todo "Worker secret NTFY_TOPIC (no topic known on this machine)"
elif ! cfq workers secrets list --worker "$WORKER_NAME" >"$TMP/worker-secrets.json"; then
  # 10007 is Cloudflare's "this Worker does not exist".
  if grep -q '10007' "$CF_ERR"; then
    note "There is no Worker called \"$WORKER_NAME\" yet. That is expected before"
    note "the first deploy (#33). Rerun this wizard afterwards: the stages before"
    note "this one will find everything in place and this one will set the secret."
    note "Or #33 can upload it at deploy time: cf deploy --secrets-file <file>."
    WORKER_SECRET="pending the first deploy"
    todo "Worker secret NTFY_TOPIC on \"$WORKER_NAME\" (rerun after the first deploy)"
  else
    cf_error
    todo "Worker secret NTFY_TOPIC on \"$WORKER_NAME\" (could not read the Worker's secrets; rerun)"
  fi
else
  if jq -e 'any(.[]?; .name == "NTFY_TOPIC")' "$TMP/worker-secrets.json" >/dev/null 2>&1; then
    WORKER_SECRET="set"
    question="\"$WORKER_NAME\" already has NTFY_TOPIC. Overwrite it with the topic in $ENV_FILE? This deploys a new version."
  else
    question="Set NTFY_TOPIC on \"$WORKER_NAME\"? This deploys a new version of the Worker."
  fi
  if confirm "$question"; then
    # The value travels in jq's environment and a file in a 0700 directory,
    # never in argv.
    NTFY_TOPIC="$NTFY_TOPIC" jq -n '{name: "NTFY_TOPIC", type: "secret_text", text: env.NTFY_TOPIC}' >"$TMP/secret.json"
    if cf workers secrets update NTFY_TOPIC --worker "$WORKER_NAME" --body "@$TMP/secret.json" </dev/null >/dev/null 2>&1; then
      ok "set NTFY_TOPIC on \"$WORKER_NAME\""
      WORKER_SECRET="set"
    else
      todo "Worker secret NTFY_TOPIC on \"$WORKER_NAME\" (cf refused; output hidden because it may hold the value)"
    fi
    rm -f "$TMP/secret.json"
  elif [[ "$WORKER_SECRET" == "set" ]]; then
    ok "keeping the Worker's existing NTFY_TOPIC"
  else
    todo "Worker secret NTFY_TOPIC on \"$WORKER_NAME\""
  fi
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Branch protection on main"
say "main takes changes only through a pull request with green CI. No reviewer"
say "is required."
protection_api="repos/$REPO/branches/main/protection"
bp_probe() { gh api "$protection_api" 2>/dev/null || true; }
current=$(bp_probe)
current_message=$(jq -r '.message // empty' <<<"$current" 2>/dev/null || true)
while [[ "$current_message" == *"Upgrade to GitHub"* ]]; do
  warn "GitHub will not protect branches of this repository on your current plan."
  say "$REPO is private, and private repositories get branch protection only"
  say "on a paid plan. Two ways through, your call:"
  step "Upgrade your account to GitHub Pro (github.com/settings/billing), or"
  step "make the repository public (Settings, General, Danger Zone). That also"
  note "  makes every issue public, including the ids this wizard records on #$ISSUE."
  open_url "https://github.com/$REPO/settings"
  if ! confirm "Done one of them? Check again (n skips this stage)"; then break; fi
  current=$(bp_probe)
  current_message=$(jq -r '.message // empty' <<<"$current" 2>/dev/null || true)
done

if [[ "$current_message" == *"Upgrade to GitHub"* ]]; then
  BRANCH_PROTECTION="NOT DONE: unavailable for a private repository on the current GitHub plan"
  todo "branch protection on main (needs GitHub Pro or a public repository)"
else
  existing_checks=$(jq -r '.required_status_checks.contexts[]?' <<<"$current" 2>/dev/null || true)
  seen_checks=$(gh pr list --repo "$REPO" --state all --limit 10 --json statusCheckRollup \
    -q '.[].statusCheckRollup[] | (.name // .context)' 2>/dev/null || true)
  candidates=$(printf '%s\n%s\n' "$existing_checks" "$seen_checks" | sed '/^$/d' | sort -u)
  checks=""
  if [[ -z "$candidates" ]]; then
    note "No CI checks have run on any pull request yet; they arrive with #33."
    note "The pull-request rule goes on now. Rerun this wizard once #33's checks"
    note "have run on a pull request and this stage will offer to require them."
  else
    say "Checks seen on recent pull requests, or already required:"
    while IFS= read -r line; do printf '      %s\n' "$line"; done <<<"$candidates"
    note "Require the CI checks. Leave out anything that is not CI, such as a"
    note "preview deploy that may be skipped."
    printf '  %sEnter requires them all; or type names separated by commas; or "none":%s ' "$BOLD" "$RESET"
    read -r reply || true
    case "$reply" in
      "")   checks="$candidates" ;;
      none) checks="" ;;
      *)    checks=$(tr ',' '\n' <<<"$reply" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d') ;;
    esac
  fi
  # Held by default: you are the only committer and an admin, so an exemption
  # for admins would leave main open to direct pushes.
  enforce_admins=true
  if confirm "Exempt repository admins (you, and agents pushing as you), so they can still push straight to main?"; then
    enforce_admins=false
  fi
  jq -n --arg checks "$checks" --argjson admins "$enforce_admins" '
    ($checks | split("\n") | map(select(length > 0))) as $c
    | {
        required_status_checks: (if ($c | length) > 0 then {strict: false, contexts: $c} else null end),
        enforce_admins: $admins,
        required_pull_request_reviews: {required_approving_review_count: 0},
        restrictions: null
      }' >"$TMP/protection.json"
  wanted=$(jq -c '{
      pr: true, reviewers: .required_pull_request_reviews.required_approving_review_count,
      admins: .enforce_admins, checks: ((.required_status_checks.contexts // []) | sort)
    }' "$TMP/protection.json")
  in_place=$(jq -c '{
      pr: (.required_pull_request_reviews != null),
      reviewers: (.required_pull_request_reviews.required_approving_review_count // null),
      admins: (.enforce_admins.enabled // false), checks: ((.required_status_checks.contexts // []) | sort)
    }' <<<"$current" 2>/dev/null || true)
  describe_protection() {
    if [[ -n "$checks" ]]; then
      printf 'pull request required, 0 reviewers, admins held: %s, required checks: %s' \
        "$enforce_admins" "$(paste -sd, <<<"$checks" | sed 's/,/, /g')"
    else
      printf 'pull request required, 0 reviewers, admins held: %s, required checks: NONE YET (rerun after #33)' "$enforce_admins"
    fi
  }
  if [[ "$wanted" == "$in_place" ]]; then
    ok "main is already protected exactly like that"
    BRANCH_PROTECTION=$(describe_protection)
    [[ -n "$checks" ]] || todo "branch protection: require the CI checks (rerun after #33)"
  elif confirm "Apply this protection to main on $REPO?"; then
    if gh api -X PUT "$protection_api" --input "$TMP/protection.json" >/dev/null 2>"$TMP/gh.err"; then
      ok "main is protected"
      BRANCH_PROTECTION=$(describe_protection)
      [[ -n "$checks" ]] || todo "branch protection: require the CI checks (rerun after #33)"
    else
      sed 's/^/      /' "$TMP/gh.err" | head -n 5
      todo "branch protection on main (GitHub refused)"
    fi
  else
    todo "branch protection on main"
  fi
fi
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Record names and ids on issue #$ISSUE"
say "The issues that follow read these from the issue. Names and ids only: no"
say "token, no topic, no email address."
or_not_done() { printf '%s' "${1:-NOT DONE}"; }
# The backticks below are Markdown, not command substitutions.
# shellcheck disable=SC2016
{
  printf '%s\n' "$COMMENT_MARKER"
  printf '## Account setup: names and ids\n\n'
  printf 'Written by `scripts/account-setup.sh` on %s. Rerunning the script replaces this comment. No secret values are recorded here.\n\n' "$(date -u +%Y-%m-%d)"
  printf '| What | Name | Id or state |\n| --- | --- | --- |\n'
  printf '| Cloudflare account | | `%s` |\n' "$(or_not_done "$CLOUDFLARE_ACCOUNT_ID")"
  printf '| Workers Paid | | %s |\n' "$(or_not_done "$WORKERS_PAID")"
  printf '| KV namespace, production | `%s` | `%s` |\n' "$KV_TITLE" "$(or_not_done "$KV_ID")"
  printf '| KV namespace, preview | `%s` | `%s` |\n' "$KV_PREVIEW_TITLE" "$(or_not_done "$KV_PREVIEW_ID")"
  printf '| D1 database, production | `%s` | `%s` |\n' "$D1_NAME" "$(or_not_done "$D1_ID")"
  printf '| D1 database, preview | `%s` | `%s` |\n' "$D1_PREVIEW_NAME" "$(or_not_done "$D1_PREVIEW_ID")"
  printf '| Zone | `%s` | `%s` (%s) |\n' "$ZONE_NAME" "$(or_not_done "$ZONE_ID")" "$(or_not_done "$ZONE_STATUS")"
  printf '| Hostname | `%s` | existing DNS records: %s. Attached as a Worker custom domain by the first deploy (#33) |\n' "$SITE_HOST" "$(or_not_done "$DNS_RECORDS")"
  printf '| Access application | %s | `%s` |\n' "$ACCESS_APP_NAME" "$(or_not_done "$ACCESS_APP_ID")"
  printf '| Access audience (AUD) | | `%s` |\n' "$(or_not_done "$ACCESS_AUD")"
  printf '| Access team domain | | `%s` |\n' "$(or_not_done "$ACCESS_TEAM_DOMAIN")"
  printf '| Access policy | %s | %s |\n' "$ACCESS_POLICY_NAME" "$(or_not_done "$ACCESS_POLICY")"
  printf '| AI Gateway | `%s` | `%s` |\n' "$AI_GATEWAY_NAME" "$(or_not_done "$AI_GATEWAY_ID")"
  printf '| Worker | `%s` | created by the first deploy (#33) |\n' "$(or_not_done "$WORKER_NAME")"
  printf '| GitHub Actions secret | `CLOUDFLARE_API_TOKEN` | %s (token named "%s") |\n' "$(or_not_done "$TOKEN_SECRET")" "$API_TOKEN_NAME"
  printf '| GitHub Actions secret | `CLOUDFLARE_ACCOUNT_ID` | %s |\n' "$(or_not_done "$ACCOUNT_SECRET")"
  printf '| GitHub Actions secret | `NTFY_TOPIC` | %s |\n' "$(or_not_done "$NTFY_SECRET")"
  printf '| Worker secret | `NTFY_TOPIC` | %s |\n' "$(or_not_done "$WORKER_SECRET")"
  printf '| ntfy on the phone | server `ntfy.sh` | %s |\n' "$(or_not_done "$NTFY_PHONE")"
  printf '| Branch protection on `main` | | %s |\n' "$(or_not_done "$BRANCH_PROTECTION")"
  printf '| Local env file | `%s` (gitignored) | holds the ids above, the Worker name and the ntfy topic |\n' "$ENV_FILE"
  if (( ${#SKIPPED[@]} )); then
    printf '\n### Still to do\n\n'
    for item in "${SKIPPED[@]}"; do printf -- '- %s\n' "$item"; done
  fi
} >"$TMP/comment.md"

sed 's/^/    /' "$TMP/comment.md"
printf '\n'
if confirm "Post this on issue #$ISSUE?"; then
  listed=true
  comment_id=$(gh api "repos/$REPO/issues/$ISSUE/comments" --paginate \
    -q ".[] | select(.body | contains(\"$COMMENT_MARKER\")) | .id" 2>/dev/null | tail -n 1) || listed=false
  if ! $listed; then
    cp "$TMP/comment.md" account-setup-comment.md # gitignored
    todo "could not read issue #$ISSUE's comments; the text is saved in account-setup-comment.md"
  elif [[ -n "$comment_id" ]] && gh api -X PATCH "repos/$REPO/issues/comments/$comment_id" -F "body=@$TMP/comment.md" >/dev/null 2>&1; then
    ok "updated the wizard's comment on issue #$ISSUE"
  elif [[ -z "$comment_id" ]] && gh issue comment "$ISSUE" --repo "$REPO" --body-file "$TMP/comment.md" >/dev/null 2>&1; then
    ok "commented on issue #$ISSUE"
  else
    cp "$TMP/comment.md" account-setup-comment.md # gitignored
    todo "could not post to issue #$ISSUE; the text is saved in account-setup-comment.md"
  fi
else
  todo "record the names and ids on issue #$ISSUE (rerun and say yes)"
fi
pause

finish
